-- THIS APPLICATION IS BASED ON SCHEMA FIRST SO WE DONT NEED TO ADD ANY MIGRATION SUPPORT FOR AUTO DDL
-- WE NEED TO CREATE DATABASE AND TABLE MANUALLY BY USING THIS SCRIPT

CREATE DATABASE EMPLOYEE_DB;

CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE EMPLOYEE (
    ID              UUID PRIMARY KEY,
    NAME            VARCHAR(50) NOT NULL,
    EMAIL           VARCHAR(50) NOT NULL,
    CONTACT_NO      VARCHAR(20) NOT NULL,
    COMPANY_NAME    VARCHAR(50),
    DESIGNATION     VARCHAR(50),
    SALARY          BIGINT,

    CONSTRAINT UK_EMPLOYEE UNIQUE (EMAIL)
);

CREATE INDEX ON EMPLOYEE USING gist (NAME gist_trgm_ops);
CREATE INDEX ON EMPLOYEE USING gist (EMAIL gist_trgm_ops);
